# Generated by Django 2.0.4 on 2018-05-23 14:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
import planotrabalho.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conselheiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('segmento', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('situacao', models.CharField(blank=True, choices=[('1', 'Habilitado'), ('0', 'Desabilitado')], default=1, max_length=1, null=True)),
                ('data_cadastro', models.DateField(blank=True, null=True)),
                ('data_situacao', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConselhoCultural',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to=planotrabalho.models.upload_to_componente)),
                ('data_envio', models.DateField(default=datetime.date.today)),
                ('ata_regimento_aprovado', models.FileField(blank=True, max_length=255, null=True, upload_to='regimentos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CriacaoSistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to=planotrabalho.models.upload_to_componente)),
                ('data_envio', models.DateField(default=datetime.date.today)),
                ('minuta_projeto_lei', models.FileField(blank=True, max_length=255, null=True, upload_to='minuta_lei')),
                ('lei_sistema_cultura', models.FileField(blank=True, max_length=255, null=True, upload_to='leis_sistema_cultura')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FundoCultura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to=planotrabalho.models.upload_to_componente)),
                ('data_envio', models.DateField(default=datetime.date.today)),
                ('cnpj_fundo_cultura', models.CharField(blank=True, default=None, max_length=18, null=True, verbose_name='CNPJ')),
                ('lei_fundo_cultura', models.FileField(blank=True, max_length=255, null=True, upload_to='lei_fundo_cultura')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrgaoGestor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to=planotrabalho.models.upload_to_componente)),
                ('data_envio', models.DateField(default=datetime.date.today)),
                ('relatorio_atividade_secretaria', models.FileField(blank=True, max_length=255, null=True, upload_to='relatorio_atividades')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanoCultura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to=planotrabalho.models.upload_to_componente)),
                ('data_envio', models.DateField(default=datetime.date.today)),
                ('relatorio_diretrizes_aprovadas', models.FileField(blank=True, max_length=255, null=True, upload_to='relatorio_diretrizes')),
                ('minuta_preparada', models.FileField(blank=True, max_length=255, null=True, upload_to='minuta_preparada')),
                ('ata_reuniao_aprovacao_plano', models.FileField(blank=True, max_length=255, null=True, upload_to='ata_aprovacao_plano')),
                ('ata_votacao_projeto_lei', models.FileField(blank=True, max_length=255, null=True, upload_to='ata_votacao_lei')),
                ('lei_plano_cultura', models.FileField(blank=True, max_length=255, null=True, upload_to='lei_plano_cultura')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanoTrabalho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conselho_cultural', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planotrabalho.ConselhoCultural')),
                ('criacao_sistema', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planotrabalho.CriacaoSistema')),
                ('fundo_cultura', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planotrabalho.FundoCultura')),
                ('orgao_gestor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planotrabalho.OrgaoGestor')),
                ('plano_cultura', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planotrabalho.PlanoCultura')),
            ],
        ),
        migrations.CreateModel(
            name='SituacoesArquivoPlano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=75)),
            ],
        ),
        migrations.AddField(
            model_name='planocultura',
            name='situacao',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='planocultura_situacao', to='planotrabalho.SituacoesArquivoPlano'),
        ),
        migrations.AddField(
            model_name='planocultura',
            name='situacao_lei_plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planotrabalho.SituacoesArquivoPlano'),
        ),
        migrations.AddField(
            model_name='orgaogestor',
            name='situacao',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='orgaogestor_situacao', to='planotrabalho.SituacoesArquivoPlano'),
        ),
        migrations.AddField(
            model_name='orgaogestor',
            name='situacao_relatorio_secretaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planotrabalho.SituacoesArquivoPlano'),
        ),
        migrations.AddField(
            model_name='fundocultura',
            name='situacao',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='fundocultura_situacao', to='planotrabalho.SituacoesArquivoPlano'),
        ),
        migrations.AddField(
            model_name='fundocultura',
            name='situacao_lei_plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planotrabalho.SituacoesArquivoPlano'),
        ),
        migrations.AddField(
            model_name='criacaosistema',
            name='situacao',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='criacaosistema_situacao', to='planotrabalho.SituacoesArquivoPlano'),
        ),
        migrations.AddField(
            model_name='criacaosistema',
            name='situacao_lei_sistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planotrabalho.SituacoesArquivoPlano'),
        ),
        migrations.AddField(
            model_name='conselhocultural',
            name='situacao',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='conselhocultural_situacao', to='planotrabalho.SituacoesArquivoPlano'),
        ),
        migrations.AddField(
            model_name='conselhocultural',
            name='situacao_ata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planotrabalho.SituacoesArquivoPlano'),
        ),
        migrations.AddField(
            model_name='conselheiro',
            name='conselho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planotrabalho.ConselhoCultural'),
        ),
    ]
