# Generated by Django 2.0.6 on 2018-07-03 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planotrabalho', '0004_migra_situacao_20180418_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conselhocultural',
            name='situacao_ata',
        ),
        migrations.RemoveField(
            model_name='criacaosistema',
            name='situacao_lei_sistema',
        ),
        migrations.RemoveField(
            model_name='fundocultura',
            name='situacao_lei_plano',
        ),
        migrations.RemoveField(
            model_name='orgaogestor',
            name='situacao_relatorio_secretaria',
        ),
        migrations.RemoveField(
            model_name='planocultura',
            name='situacao_lei_plano',
        ),
    ]
