# Generated by Django 2.0.8 on 2018-09-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planotrabalho', '0005_componente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='tipo',
            field=models.IntegerField(choices=[(0, 'Lei Sistema'), (1, 'Órgão Gestor'), (2, 'Fundo Cultura'), (3, 'Conselho Cultural'), (4, 'Plano Cultura')], default=0),
        ),
    ]
