# Generated by Django 2.0.8 on 2018-10-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planotrabalho', '0007_componente_diligencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='data_publicacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Publicação do Componente'),
        ),
    ]
