# Generated by Django 2.0.8 on 2019-02-01 17:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
import planotrabalho.models


class Migration(migrations.Migration):

    dependencies = [
        ('planotrabalho', '0012_auto_20181218_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoComponente2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to=planotrabalho.models.upload_to)),
                ('situacao', models.IntegerField(choices=[(0, 'Em preenchimento'), (1, 'Avaliando anexo'), (2, 'Concluída'), (3, 'Arquivo aprovado com ressalvas'), (4, 'Arquivo danificado'), (5, 'Arquivo incompleto'), (6, 'Arquivo incorreto')], default=0, verbose_name='Situação do Arquivo')),
                ('data_envio', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.RemoveField(
            model_name='componente',
            name='arquivo',
        ),
        migrations.RemoveField(
            model_name='componente',
            name='data_envio',
        ),
        migrations.RemoveField(
            model_name='componente',
            name='id',
        ),
        migrations.RemoveField(
            model_name='componente',
            name='situacao',
        ),
        migrations.AddField(
            model_name='componente',
            name='arquivocomponente2_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='planotrabalho.ArquivoComponente2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fundodecultura',
            name='regulamentacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fundos', to='planotrabalho.ArquivoComponente2'),
        ),
    ]
