# Generated by Django 2.0.8 on 2019-02-08 19:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
import planotrabalho.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0008_merge_20181010_1518'),
        ('planotrabalho', '0013_auto_20190207_1517'),
    ]

    def copia_dados_para_nova_estrutura(apps, schema_editor):
        Componente = apps.get_model('planotrabalho', 'Componente')
        Componente2 = apps.get_model('planotrabalho', 'Componente2')
        componente_fields = ()

        FundoDeCultura = apps.get_model('planotrabalho', 'FundoDeCultura')
        FundoDeCultura2 = apps.get_model('planotrabalho', 'FundoDeCultura2')
        fundo_fields = ('id', 'arquivo', 'situacao', 'data_envio', 'tipo',
                        'diligencia', 'data_publicacao', 'componente_ptr', 'cnpj')

        ArquivoComponente3 = apps.get_model(
            'planotrabalho', 'ArquivoComponente3')

        for fundo in FundoDeCultura.objects.all():
            novo_fundo = FundoDeCultura2()

            for field in fundo._meta.fields:
                value = getattr(fundo, field.name)
                setattr(novo_fundo, field.name, value)

            novo_fundo.save()

        for componente in Componente.objects.all():
            novo_componente = Componente2()

            for field in componente._meta.fields:
                value = getattr(componente, field.name)
                setattr(novo_componente, field.name, value)

    operations = [
        migrations.CreateModel(
            name='ArquivoComponente3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to=planotrabalho.models.upload_to)),
                ('situacao', models.IntegerField(choices=[(0, 'Em preenchimento'), (1, 'Avaliando anexo'), (2, 'Concluída'), (3, 'Arquivo aprovado com ressalvas'), (4, 'Arquivo danificado'), (5, 'Arquivo incompleto'), (6, 'Arquivo incorreto')], default=0, verbose_name='Situação do Arquivo')),
                ('data_envio', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Componente2',
            fields=[
                ('arquivocomponente3_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='planotrabalho.ArquivoComponente3')),
                ('tipo', models.IntegerField(choices=[(0, 'Lei Sistema'), (1, 'Órgão Gestor'), (2, 'Fundo Cultura'), (3, 'Conselho Cultural'), (4, 'Plano Cultura')], default=0)),
                ('data_publicacao', models.DateField(blank=True, null=True, verbose_name='Data de Publicação do Componente')),
            ],
            bases=('planotrabalho.arquivocomponente3',),
        ),
        migrations.CreateModel(
            name='FundoDeCultura2',
            fields=[
                ('componente2_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='planotrabalho.Componente2')),
                ('cnpj', models.CharField(blank=True, default=None, max_length=18, null=True, verbose_name='CNPJ')),
            ],
            bases=('planotrabalho.componente2',),
        ),
        migrations.AddField(
            model_name='componente2',
            name='diligencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao.DiligenciaSimples'),
        ),
        migrations.RunPython(
            copia_dados_para_nova_estrutura,
            migrations.RunPython.noop
        ),
    ]
