# Generated by Django 2.0.8 on 2019-02-26 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planotrabalho', '0017_auto_20190221_1513'),
    ]

    operations = [
	    migrations.RunSQL(
	            "SELECT setval('planotrabalho_arquivocomponente3_id_seq', 10000)"
	        ),
    ]
