# Generated by Django 2.0.8 on 2019-03-11 13:58

from django.db import migrations

def migra_conselho_de_cultura(apps, schema_editor):
    Componente = apps.get_model('planotrabalho', 'Componente')
    ConselhoDeCultura = apps.get_model('planotrabalho', 'ConselhoDeCultura')

    CONSELHO = 3
    for componente in Componente.objects.filter(tipo=CONSELHO):
        conselho = ConselhoDeCultura()
        conselho.componente_ptr = componente
        conselho.save()

        componente.conselhodecultura = conselho
        componente.save()


class Migration(migrations.Migration):

    dependencies = [
        ('planotrabalho', '0020_conselhodecultura'),
    ]

    operations = [
        migrations.RunPython(migra_conselho_de_cultura)
    ]
