# Generated by Django 2.0.8 on 2019-03-13 22:22

from django.db import migrations, models
import django.db.models.deletion

def migra_conselheiro_fk(apps, schema_editor):
    Conselheiro = apps.get_model('planotrabalho', 'Conselheiro')
    ConselhoDeCultura = apps.get_model('planotrabalho', 'ConselhoDeCultura')

    for conselheiro in Conselheiro.objects.all():
        conselho_de_cultura = ConselhoDeCultura.objects.get(
            componente_ptr_id=conselheiro.conselho.id)
        conselheiro.conselho_aux = conselho_de_cultura
        conselheiro.save()


class Migration(migrations.Migration):

    dependencies = [
        ('planotrabalho', '0022_auto_20190315_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='conselheiro',
            name='conselho_aux',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conselho_aux', to='planotrabalho.ConselhoDeCultura'),
            preserve_default=False,
        ),
        migrations.RunPython(migra_conselheiro_fk),
        migrations.RemoveField(
            model_name='conselheiro',
            name='conselho',
        ),
        migrations.RenameField(
            model_name='conselheiro',
            old_name='conselho_aux',
            new_name='conselho',
        ),
    ]
