# Generated by Django 2.0.8 on 2019-03-20 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planotrabalho', '0023_conselheiro_conselho_aux'),
        ('planotrabalho', '0013_auto_20190228_1818'),
    ]

    operations = [
    ]
