# Generated by Django 2.0.8 on 2019-03-20 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planotrabalho', '0024_merge_20190320_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conselheiro',
            name='conselho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planotrabalho.ConselhoDeCultura'),
        ),
    ]
