INSERT INTO adesao_uf(codigo_ibge, sigla, nome_uf) VALUES (11,'RO','Rondônia');
INSERT INTO adesao_uf(codigo_ibge, sigla, nome_uf) VALUES (12,'AC','Acre');
INSERT INTO adesao_uf(codigo_ibge, sigla, nome_uf) VALUES (13,'AM','Amazonas');
INSERT INTO adesao_uf(codigo_ibge, sigla, nome_uf) VALUES (14,'RR','Roraima');
INSERT INTO adesao_uf(codigo_ibge, sigla, nome_uf) VALUES (15,'PA','Pará');
INSERT INTO adesao_uf(codigo_ibge, sigla, nome_uf) VALUES (16,'AP','Amapá');
INSERT INTO adesao_uf(codigo_ibge, sigla, nome_uf) VALUES (17,'TO','Tocantins');
INSERT INTO adesao_uf(codigo_ibge, sigla, nome_uf) VALUES (21,'MA','Maranhão');
INSERT INTO adesao_uf(codigo_ibge, sigla, nome_uf) VALUES (22,'PI','Piauí');
INSERT INTO adesao_uf(codigo_ibge, sigla, nome_uf) VALUES (23,'CE','Ceará');
INSERT INTO adesao_uf(codigo_ibge, sigla, nome_uf) VALUES (24,'RN','Rio Grande do Norte');
INSERT INTO adesao_uf(codigo_ibge, sigla, nome_uf) VALUES (25,'PB','Paraíba');
INSERT INTO adesao_uf(codigo_ibge, sigla, nome_uf) VALUES (26,'PE','Pernambuco');
INSERT INTO adesao_uf(codigo_ibge, sigla, nome_uf) VALUES (27,'AL','Alagoas');
INSERT INTO adesao_uf(codigo_ibge, sigla, nome_uf) VALUES (28,'SE','Sergipe');
INSERT INTO adesao_uf(codigo_ibge, sigla, nome_uf) VALUES (29,'BA','Bahia');
INSERT INTO adesao_uf(codigo_ibge, sigla, nome_uf) VALUES (31,'MG','Minas Gerais');
INSERT INTO adesao_uf(codigo_ibge, sigla, nome_uf) VALUES (32,'ES','Espírito Santo');
INSERT INTO adesao_uf(codigo_ibge, sigla, nome_uf) VALUES (33,'RJ','Rio de Janeiro');
INSERT INTO adesao_uf(codigo_ibge, sigla, nome_uf) VALUES (35,'SP','São Paulo');
INSERT INTO adesao_uf(codigo_ibge, sigla, nome_uf) VALUES (41,'PR','Paraná');
INSERT INTO adesao_uf(codigo_ibge, sigla, nome_uf) VALUES (42,'SC','Santa Catarina');
INSERT INTO adesao_uf(codigo_ibge, sigla, nome_uf) VALUES (43,'RS','Rio Grande do Sul');
INSERT INTO adesao_uf(codigo_ibge, sigla, nome_uf) VALUES (50,'MS','Mato Grosso do Sul');
INSERT INTO adesao_uf(codigo_ibge, sigla, nome_uf) VALUES (51,'MT','Mato Grosso');
INSERT INTO adesao_uf(codigo_ibge, sigla, nome_uf) VALUES (52,'GO','Goiás');
INSERT INTO adesao_uf(codigo_ibge, sigla, nome_uf) VALUES (53,'DF','Distrito Federal');
