# Generated by Django 2.0.4 on 2018-05-23 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planotrabalho', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ibge', models.IntegerField(unique=True)),
                ('nome_municipio', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
            options={
                'ordering': ['nome_municipio'],
            },
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(blank=True, choices=[('0', 'Aguardando preenchimento dos dados cadastrais'), ('1', 'Aguardando envio da documentação'), ('2', 'Documentação Recebida - Aguarda Análise'), ('3', 'Diligência Documental'), ('4', 'Encaminhado para assinatura do Secretário SAI'), ('5', 'Aguarda Publicação no DOU'), ('6', 'Publicado no DOU'), ('7', 'Responsável confirmado')], max_length=1, null=True)),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='historico')),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao', models.CharField(blank=True, max_length=50)),
                ('numero_processo', models.CharField(blank=True, max_length=50)),
                ('cpf_prefeito', models.CharField(max_length=14, verbose_name='CPF')),
                ('nome_prefeito', models.CharField(max_length=255)),
                ('cnpj_prefeitura', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('rg_prefeito', models.CharField(max_length=50, verbose_name='RG')),
                ('orgao_expeditor_rg', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=255)),
                ('complemento', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=50)),
                ('telefone_um', models.CharField(max_length=100)),
                ('telefone_dois', models.CharField(blank=True, max_length=25)),
                ('telefone_tres', models.CharField(blank=True, max_length=25)),
                ('endereco_eletronico', models.URLField(blank=True, max_length=255, null=True)),
                ('email_institucional_prefeito', models.EmailField(max_length=254)),
                ('termo_posse_prefeito', models.FileField(blank=True, max_length=255, null=True, upload_to='termo_posse')),
                ('rg_copia_prefeito', models.FileField(blank=True, max_length=255, null=True, upload_to='rg_copia')),
                ('cpf_copia_prefeito', models.FileField(blank=True, max_length=255, null=True, upload_to='cpf_copia')),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_responsavel', models.CharField(max_length=14, verbose_name='CPF')),
                ('rg_responsavel', models.CharField(max_length=25, verbose_name='RG')),
                ('orgao_expeditor_rg', models.CharField(max_length=50)),
                ('nome_responsavel', models.CharField(max_length=100)),
                ('cargo_responsavel', models.CharField(max_length=100)),
                ('instituicao_responsavel', models.CharField(max_length=100)),
                ('telefone_um', models.CharField(max_length=25)),
                ('telefone_dois', models.CharField(blank=True, max_length=25)),
                ('telefone_tres', models.CharField(blank=True, max_length=25)),
                ('email_institucional_responsavel', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Secretario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_secretario', models.CharField(max_length=14, verbose_name='CPF')),
                ('rg_secretario', models.CharField(max_length=25, verbose_name='RG')),
                ('orgao_expeditor_rg', models.CharField(max_length=50)),
                ('nome_secretario', models.CharField(max_length=100)),
                ('cargo_secretario', models.CharField(max_length=100)),
                ('instituicao_secretario', models.CharField(max_length=100)),
                ('telefone_um', models.CharField(max_length=25)),
                ('telefone_dois', models.CharField(blank=True, max_length=25)),
                ('telefone_tres', models.CharField(blank=True, max_length=25)),
                ('email_institucional_secretario', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Uf',
            fields=[
                ('codigo_ibge', models.IntegerField(primary_key=True, serialize=False)),
                ('sigla', models.CharField(max_length=2)),
                ('nome_uf', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['sigla'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.CharField(max_length=100)),
                ('estado_processo', models.CharField(choices=[('0', 'Aguardando preenchimento dos dados cadastrais'), ('1', 'Aguardando envio da documentação'), ('2', 'Documentação Recebida - Aguarda Análise'), ('3', 'Diligência Documental'), ('4', 'Encaminhado para assinatura do Secretário SAI'), ('5', 'Aguarda Publicação no DOU'), ('6', 'Publicado no DOU'), ('7', 'Responsável confirmado')], default='0', max_length=1)),
                ('data_publicacao_acordo', models.DateField(blank=True, null=True)),
                ('codigo_ativacao', models.CharField(max_length=12, unique=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('prazo', models.IntegerField(default=2)),
                ('municipio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adesao.Municipio')),
                ('plano_trabalho', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planotrabalho.PlanoTrabalho')),
                ('responsavel', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adesao.Responsavel')),
                ('secretario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adesao.Secretario')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='secretario',
            name='estado_expeditor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adesao.Uf'),
        ),
        migrations.AddField(
            model_name='responsavel',
            name='estado_expeditor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adesao.Uf'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adesao.Uf'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adesao.Cidade'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='estado_expeditor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado_expeditor', to='adesao.Uf'),
        ),
        migrations.AddField(
            model_name='historico',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adesao.Usuario'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adesao.Uf'),
        ),
        migrations.AlterUniqueTogether(
            name='municipio',
            unique_together={('cidade', 'estado')},
        ),
    ]
