# Generated by Django 2.0.6 on 2018-07-03 19:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SistemaCultura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='link_publicacao_acordo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='processo_sei',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sistemacultura',
            name='cadastrador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adesao.Usuario'),
        ),
        migrations.AddField(
            model_name='sistemacultura',
            name='cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adesao.Cidade'),
        ),
        migrations.AddField(
            model_name='sistemacultura',
            name='uf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adesao.Uf'),
        ),
    ]
