# Generated by Django 2.0.4 on 2018-07-06 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0002_auto_20180703_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adesao.Cidade'),
        ),
    ]
