# Generated by Django 2.0.8 on 2018-09-13 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planotrabalho', '0005_componente'),
        ('adesao', '0003_auto_20180706_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('rg', models.CharField(max_length=25, verbose_name='RG')),
                ('orgao_expeditor_rg', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('instituicao', models.CharField(max_length=100)),
                ('telefone_um', models.CharField(max_length=25)),
                ('telefone_dois', models.CharField(blank=True, max_length=25)),
                ('telefone_tres', models.CharField(blank=True, max_length=25)),
                ('email_institucional', models.EmailField(max_length=254)),
                ('tipo_funcionario', models.IntegerField(choices=[(0, 'Secretário'), (1, 'Responsável')], default='0')),
                ('estado_expeditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adesao.Uf')),
            ],
        ),
        migrations.AddField(
            model_name='sistemacultura',
            name='conselho',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conselho', to='planotrabalho.Componente'),
        ),
        migrations.AddField(
            model_name='sistemacultura',
            name='fundo_cultura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fundo_cultura', to='planotrabalho.Componente'),
        ),
        migrations.AddField(
            model_name='sistemacultura',
            name='legislacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legislacao', to='planotrabalho.Componente'),
        ),
        migrations.AddField(
            model_name='sistemacultura',
            name='orgao_gestor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orgao_gestor', to='planotrabalho.Componente'),
        ),
        migrations.AddField(
            model_name='sistemacultura',
            name='plano',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plano', to='planotrabalho.Componente'),
        ),
        migrations.AddField(
            model_name='sistemacultura',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sistema_cultura_responsavel', to='adesao.Funcionario'),
        ),
        migrations.AddField(
            model_name='sistemacultura',
            name='secretario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sistema_cultura_secretario', to='adesao.Funcionario'),
        ),
    ]
