# Generated by Django 2.0.8 on 2018-09-13 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0004_auto_20180913_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao', models.CharField(blank=True, max_length=50)),
                ('cnpj', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('endereco', models.CharField(max_length=255)),
                ('complemento', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=50)),
                ('telefone_um', models.CharField(max_length=100)),
                ('telefone_dois', models.CharField(blank=True, max_length=25)),
                ('telefone_tres', models.CharField(blank=True, max_length=25)),
                ('endereco_eletronico', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sistemacultura',
            name='sede',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adesao.Sede'),
        ),
    ]
