# Generated by Django 2.0.8 on 2018-09-13 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0005_auto_20180913_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('funcionario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adesao.Funcionario')),
                ('termo_posse', models.FileField(blank=True, max_length=255, null=True, upload_to='termo_posse')),
            ],
            bases=('adesao.funcionario',),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='tipo_funcionario',
            field=models.IntegerField(choices=[(0, 'Secretário'), (1, 'Responsável'), (2, 'Gestor')], default='0'),
        ),
        migrations.AddField(
            model_name='sistemacultura',
            name='gestor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adesao.Gestor'),
        ),
    ]
