# Generated by Django 2.0.8 on 2018-09-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('adesao', '0007_entefederado'), ('adesao', '0008_auto_20180920_1513')]

    dependencies = [
        ('adesao', '0006_auto_20180913_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnteFederado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_ibge', models.IntegerField(verbose_name='Código IBGE')),
                ('nome', models.CharField(max_length=300, verbose_name='Nome do EnteFederado')),
                ('gentilico', models.CharField(blank=True, max_length=300, verbose_name='Gentilico', null=True)),
                ('mandatario', models.CharField(blank=True, max_length=300, null=True, verbose_name='Nome do Mandataio')),
                ('territorio', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Área territorial - km²')),
                ('populacao', models.IntegerField(verbose_name='População Estimada - pessoas')),
                ('densidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Densidade demográfica - hab/km²')),
                ('idh', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='IDH / IDHM')),
                ('receita', models.IntegerField(blank=True, null=True, verbose_name='Receitas realizadas - R$ (×1000)')),
                ('despesas', models.IntegerField(blank=True, null=True, verbose_name='Despesas empenhadas - R$ (×1000)')),
                ('pib', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PIB per capita - R$')),
            ],
        ),
        migrations.AddIndex(
            model_name='entefederado',
            index=models.Index(fields=['cod_ibge'], name='adesao_ente_cod_ibg_61ed24_idx'),
        ),
    ]
