# Generated by Django 2.0.8 on 2018-09-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0006_auto_20180913_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestor',
            name='cpf_copia',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='cpf_copia'),
        ),
        migrations.AddField(
            model_name='gestor',
            name='rg_copia',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='rg_copia'),
        ),
        migrations.AddField(
            model_name='sistemacultura',
            name='data_publicacao_acordo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sistemacultura',
            name='estado_processo',
            field=models.CharField(choices=[('0', 'Aguardando preenchimento dos dados cadastrais'), ('1', 'Aguardando envio da documentação'), ('2', 'Documentação Recebida - Aguarda Análise'), ('3', 'Diligência Documental'), ('4', 'Encaminhado para assinatura do Secretário SAI'), ('5', 'Aguarda Publicação no DOU'), ('6', 'Publicado no DOU'), ('7', 'Responsável confirmado')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='sistemacultura',
            name='link_publicacao_acordo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sistemacultura',
            name='processo_sei',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
