# Generated by Django 2.0.8 on 2018-09-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0007_auto_20180917_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemacultura',
            name='localizacao',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sistemacultura',
            name='numero_processo',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
