# Generated by Django 2.0.8 on 2018-09-20 20:09

from django.core.management import call_command
from django.db import migrations


def import_ibge_data(apps, schema_editor):
    call_command("loaddata", "ibge", format="json", verbosity=0)


class Migration(migrations.Migration):

    dependencies = [("adesao", "0007_entefederado_squashed_0008_auto_20180920_1513")]

    operations = [migrations.RunPython(import_ibge_data)]
