# Generated by Django 2.0.8 on 2018-09-20 20:09

from django.core import serializers
from django.core.management import call_command
from django.db import migrations


def import_ibge_data(apps, schema_editor):
    '''
    O loaddata por padrão vai carregar o estado do model mais atual, só que
    qualquer alteração futura nos campos de EnteFederado quebra essa migração,
    por isso é preciso trocar qual serializer é usado pelo loaddata.

    Ver: https://stackoverflow.com/questions/32912112/django-loaddata-in-migrations-errors
    '''
    original_apps = serializers.python.apps
    serializers.python.apps = apps

    call_command("loaddata", "ibge", "-i", format="json", verbosity=0)

    serializers.python.apps = original_apps


class Migration(migrations.Migration):

    dependencies = [("adesao", "0007_entefederado_squashed_0008_auto_20180920_1513")]

    operations = [migrations.RunPython(import_ibge_data)]
