# Generated by Django 2.0.8 on 2018-09-21 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0008_auto_20180917_1105'),
        ('adesao', '0008_load_ibge_data'),
    ]

    operations = [
    ]
