# Generated by Django 2.0.8 on 2018-09-24 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0009_merge_20180921_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemacultura',
            name='ente_federado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adesao.EnteFederado'),
        ),
    ]
