# Generated by Django 2.0.8 on 2018-09-27 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0005_diligenciasimples'),
        ('adesao', '0010_sistemacultura_ente_federado'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemacultura',
            name='diligencia_simples',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sistema_cultura', to='gestao.DiligenciaSimples'),
        ),
    ]
