# Generated by Django 2.0.8 on 2018-10-03 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0011_sistemacultura_diligencia'),
        ('adesao', '0011_sistemacultura_diligencia_simples'),
    ]

    operations = [
    ]
