# Generated by Django 2.0.8 on 2018-10-03 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0012_merge_20181003_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sistemacultura',
            name='diligencia',
        ),
    ]
