# Generated by Django 2.0.8 on 2018-10-03 17:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0011_sistemacultura_diligencia_simples'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sistemacultura',
            options={'ordering': ['ente_federado', '-alterado_em']},
        ),
        migrations.AddField(
            model_name='sistemacultura',
            name='alterado_em',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Alterado em'),
        ),
    ]
