# Generated by Django 2.0.8 on 2018-10-05 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0014_auto_20181003_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sistemacultura',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='sistemacultura',
            name='uf',
        ),
    ]
