# Generated by Django 2.0.8 on 2018-10-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0015_auto_20181005_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='instituicao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
