# Generated by Django 2.0.8 on 2018-10-05 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0017_auto_20181005_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sistemacultura',
            name='localizacao',
        ),
    ]
