# Generated by Django 2.0.8 on 2018-10-16 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0020_auto_20181016_1602'),
        ('adesao', '0019_auto_20181005_1645'),
    ]

    operations = [
    ]
