# Generated by Django 2.0.8 on 2018-10-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0021_merge_20181016_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistemacultura',
            name='numero_processo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
