# Generated by Django 2.0.8 on 2018-11-30 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0023_auto_20181119_1855'),
        ('planotrabalho', '0009_fundodecultura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='estado_expeditor',
            field=models.IntegerField(choices=[(11, 'RO'), (12, 'AC'), (13, 'AM'), (14, 'RR'), (15, 'PA'), (16, 'AP'), (17, 'TO'), (21, 'MA'), (22, 'PI'), (23, 'CE'), (24, 'RN'), (25, 'PB'), (26, 'PE'), (27, 'AL'), (28, 'SE'), (29, 'BA'), (31, 'MG'), (32, 'ES'), (33, 'RJ'), (35, 'SP'), (41, 'PR'), (42, 'SC'), (43, 'RS'), (50, 'MS'), (51, 'MT'), (52, 'GO'), (53, 'DF')]),
        ),
        migrations.AlterField(
            model_name='sistemacultura',
            name='fundo_cultura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fundo_cultura', to='planotrabalho.FundoDeCultura'),
        ),
    ]
