# Generated by Django 2.0.8 on 2018-11-30 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0023_auto_20181119_1855'),
        ('planotrabalho', '0009_fundodecultura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistemacultura',
            name='fundo_cultura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fundo_cultura', to='planotrabalho.FundoDeCultura'),
        ),
    ]
