# Generated by Django 2.0.8 on 2019-01-14 21:47

from django.db import migrations, models

import json


def inserir_lat_long(apps, schema_editor):
    EnteFederado = apps.get_model('adesao', 'EnteFederado')

    with open('adesao/fixtures/lat_long_ibge.json') as file:
        latlng = json.load(file)

        for c in latlng:
            ente = EnteFederado.objects.get(cod_ibge=c['cod_ibge'])
            ente.latitude = c['lat']
            ente.longitude = c['long']
            ente.save()


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0028_auto_20190116_1635'),
        ('adesao', '0024_auto_20181130_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sistemacultura',
            options={'ordering': ['ente_federado__nome', 'ente_federado', '-alterado_em']},
        ),
        migrations.AddField(
            model_name='entefederado',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entefederado',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RunPython(inserir_lat_long),
    ]
