# Generated by Django 2.0.8 on 2019-01-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0025_auto_20190114_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemacultura',
            name='prazo',
            field=models.IntegerField(default=2),
        ),
    ]
