# Generated by Django 2.0.8 on 2019-01-15 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0025_auto_20190114_1947'),
        ('adesao', '0025_auto_20190114_1504'),
    ]

    operations = [
    ]
