# Generated by Django 2.0.8 on 2019-01-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0024_auto_20181130_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemacultura',
            name='prazo',
            field=models.IntegerField(default=2),
        ),
    ]
