# Generated by Django 2.0.8 on 2019-01-15 18:48

from django.db import migrations
from django.core.exceptions import ObjectDoesNotExist


def migra_prazo(apps, schema_editor):

	SistemaCultura = apps.get_model('adesao', 'SistemaCultura')
	Municipio = apps.get_model('adesao', 'Municipio')

	for municipio in Municipio.objects.all():

		try:
			if municipio.usuario:
				if municipio.cidade:
					sistemas = SistemaCultura.objects.filter(ente_federado__nome=municipio.cidade.nome_municipio).distinct('ente_federado')
					codigo_ibge = str(municipio.cidade.codigo_ibge)
				else:
					sistemas = SistemaCultura.objects.filter(ente_federado__nome=municipio.estado.nome_uf).distinct('ente_federado')
					codigo_ibge = str(municipio.estado.codigo_ibge)

				if sistemas.count() > 1:
					for sistema in sistemas:
						if codigo_ibge in str(sistema.ente_federado.cod_ibge):
							sistema_prazo = sistema
							break
				elif sistemas.count() == 1:
					sistema_prazo = sistemas[0]
				else:
					continue

				sistema_prazo.prazo = municipio.usuario.prazo
				sistema_prazo.save()

		except ObjectDoesNotExist:
			pass


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0026_auto_20190115_1647'),
    ]

    operations = [
    	migrations.RunPython(migra_prazo),
    ]
