# Generated by Django 2.0.8 on 2019-02-08 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planotrabalho', '0014_auto_20190208_1733'),
        ('adesao', '0027_auto_20190124_1845'),
    ]

    def copia_fks(apps, schema_editor):
        SistemaCultura = apps.get_model('adesao', 'SistemaCultura')
        Componente = apps.get_model('planotrabalho', 'Componente')

        componentes = ('legislacao', 'orgao_gestor', 'fundo_cultura', 'conselho', 'plano_cultura')

        for sistema in SistemaCultura.objects.all():
            for c in componentes:
                setattr(sistema, c+'2', getattr(sistema, c))2
            sistema.save()


    operations = [
        migrations.AddField(
            model_name='sistemacultura',
            name='conselho2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conselho', to='planotrabalho.Componente2'),
        ),
        migrations.AddField(
            model_name='sistemacultura',
            name='fundo_cultura2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fundo_cultura', to='planotrabalho.FundoDeCultura2'),
        ),
        migrations.AddField(
            model_name='sistemacultura',
            name='legislacao2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legislacao', to='planotrabalho.Componente2'),
        ),
        migrations.AddField(
            model_name='sistemacultura',
            name='orgao_gestor2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orgao_gestor', to='planotrabalho.Componente2'),
        ),
        migrations.AddField(
            model_name='sistemacultura',
            name='plano2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plano', to='planotrabalho.Componente2'),
        ),
    ]
