# Generated by Django 2.0.8 on 2019-02-13 17:14

from django.db import migrations, models

def corrige_tipo_conselho_e_plano(apps, schema_editor):
	SistemaCultura = apps.get_model('adesao', 'SistemaCultura')

	for sistema in SistemaCultura.objects.distinct('ente_federado').order_by('ente_federado'):
		if sistema.conselho:
			sistema.conselho.tipo = 3
			sistema.conselho.save()
		
		if sistema.plano:
			sistema.plano.tipo = 4
			sistema.plano.save()


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0028_sistemacultura_alterado_por'),
    ]

    operations = [
    	migrations.RunPython(corrige_tipo_conselho_e_plano)
    ]
