# Generated by Django 2.0.8 on 2019-02-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0029_auto_20190213_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemacultura',
            name='conferencia_nacional',
            field=models.BooleanField(default=False),
        ),
    ]
