# Generated by Django 2.0.8 on 2019-02-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0029_auto_20190213_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entefederado',
            name='densidade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Densidade demográfica - hab/km²'),
        ),
        migrations.AlterField(
            model_name='entefederado',
            name='territorio',
            field=models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Área territorial - km²'),
        ),

    ]
