# Generated by Django 2.0.8 on 2019-02-18 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0030_auto_20190215_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sistemacultura',
            name='conselho',
        ),
        migrations.RemoveField(
            model_name='sistemacultura',
            name='fundo_cultura',
        ),
        migrations.RemoveField(
            model_name='sistemacultura',
            name='legislacao',
        ),
        migrations.RemoveField(
            model_name='sistemacultura',
            name='orgao_gestor',
        ),
        migrations.RemoveField(
            model_name='sistemacultura',
            name='plano',
        ),
    ]
