# Generated by Django 2.0.8 on 2019-02-28 22:06

from django.db import migrations
import json

def atualiza_ente_federado(apps, schema_editor):
	EnteFederado = apps.get_model('adesao', 'EnteFederado')

	json_data = open('adesao/fixtures/ibge_20190220.json')   
	data = json.load(json_data)

	for item in data:
		ente = EnteFederado.objects.get(cod_ibge=item['fields']['cod_ibge'])
		ente.idh = item['fields']['idh']
		ente.pib = item['fields']['pib']
		ente.populacao = item['fields']['populacao']
		ente.save()

class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0030_sistemacultura_conferencia_nacional'),
    ]

    operations = [
    	migrations.RunPython(atualiza_ente_federado)
    ]
