# Generated by Django 2.0.8 on 2019-02-20 23:06

from django.core import serializers
from django.core.management import call_command
from django.db import migrations


def import_ibge_data(apps, schema_editor):
    '''
    O loaddata por padrão vai carregar o estado do model mais atual, só que
    qualquer alteração futura nos campos de EnteFederado quebra essa migração,
    por isso é preciso trocar qual serializer é usado pelo loaddata.

    Ver: https://stackoverflow.com/questions/32912112/django-loaddata-in-migrations-errors
    '''
    original_apps = serializers.python.apps
    serializers.python.apps = apps

    call_command("loaddata", "ibge_20190220", "-i", format="json", verbosity=0)

    serializers.python.apps = original_apps


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0030_auto_20190220_1601'),
    ]

    operations = [
    ]
