# Generated by Django 2.0.8 on 2019-02-28 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0031_auto_20190228_1906'),
        ('adesao', '0030_auto_20190220_1601'),
    ]

    operations = [
    ]
