# Generated by Django 2.0.8 on 2019-02-21 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0031_auto_20190220_2006'),
        ('adesao', '0030_sistemacultura_conferencia_nacional'),
    ]

    operations = [
    ]
