# Generated by Django 2.0.8 on 2019-02-18 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planotrabalho', '0015_auto_20190218_1811'),
        ('adesao', '0031_auto_20190218_1800'),
    ]

    def copiar_dados(apps, schema_editor):
        SistemaCultura = apps.get_model('adesao', 'SistemaCultura')

        componentes = ('conselho', 'fundo_cultura', 'legislacao', 'orgao_gestor', 'plano')

        for sistema in SistemaCultura.objects.all():
            for componente in componentes:
                setattr(sistema, componente, getattr(sistema, componente+'2'))
            sistema.save()

    operations = [
        migrations.AddField(
            model_name='sistemacultura',
            name='conselho',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conselho', to='planotrabalho.Componente'),
        ),
        migrations.AddField(
            model_name='sistemacultura',
            name='fundo_cultura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fundo_cultura', to='planotrabalho.FundoDeCultura'),
        ),
        migrations.AddField(
            model_name='sistemacultura',
            name='legislacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legislacao', to='planotrabalho.Componente'),
        ),
        migrations.AddField(
            model_name='sistemacultura',
            name='orgao_gestor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orgao_gestor', to='planotrabalho.Componente'),
        ),
        migrations.AddField(
            model_name='sistemacultura',
            name='plano',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plano', to='planotrabalho.Componente'),
        ),
        migrations.RunPython(copiar_dados, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='sistemacultura',
            name='conselho2',
        ),
        migrations.RemoveField(
            model_name='sistemacultura',
            name='fundo_cultura2',
        ),
        migrations.RemoveField(
            model_name='sistemacultura',
            name='legislacao2',
        ),
        migrations.RemoveField(
            model_name='sistemacultura',
            name='orgao_gestor2',
        ),
        migrations.RemoveField(
            model_name='sistemacultura',
            name='plano2',
        ),
    ]
