# Generated by Django 2.0.8 on 2019-03-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0032_merge_20190221_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='email_pessoal',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
