# Generated by Django 2.0.8 on 2019-03-08 13:39

from django.db import migrations

def remove_dados_cacimbinhas(apps, schema_editor):
	SistemaCultura = apps.get_model('adesao', 'SistemaCultura')
	cacimbinhas = SistemaCultura.objects.filter(ente_federado__nome='Cacimbinhas')
	cacimbinhas.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0032_merge_20190228_1927'),
    ]

    operations = [
    	migrations.RunPython(remove_dados_cacimbinhas)
    ]
