# Generated by Django 2.0.8 on 2019-03-08 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0032_auto_20190218_1811'),
        ('adesao', '0033_auto_20190308_1039'),
    ]

    operations = [
    ]
