# Generated by Django 2.0.8 on 2019-03-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0033_auto_20190308_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='email_pessoal',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
