# Generated by Django 2.0.8 on 2019-03-20 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0034_funcionario_email_pessoal'),
        ('adesao', '0032_auto_20190218_1811'),
    ]

    operations = [
    ]
