# Generated by Django 2.0.8 on 2019-03-11 16:31

from django.db import migrations, models
import django.db.models.deletion

def copia_conselhos(apps, schema_editor):
    SistemaCultura = apps.get_model('adesao', 'SistemaCultura')
    for sistema in SistemaCultura.objects.filter(conselho__tipo=3):
        sistema.conselho_aux = sistema.conselho.conselhodecultura
        sistema.save()


class Migration(migrations.Migration):

    dependencies = [
        ('planotrabalho', '0021_auto_20190311_1058'),
        ('adesao', '0034_merge_20190308_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemacultura',
            name='conselho_aux',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conselho_aux', to='planotrabalho.ConselhoDeCultura'),
        ),
        migrations.RunPython(copia_conselhos),
        migrations.RemoveField(
            model_name='sistemacultura',
            name='conselho',
        ),
        migrations.RenameField(
            model_name='sistemacultura',
            old_name='conselho_aux',
            new_name='conselho',
        ),
    ]
