# Generated by Django 2.0.8 on 2019-03-20 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0035_merge_20190320_1124'),
        ('adesao', '0034_merge_20190308_1538'),
    ]

    operations = [
    ]
