# Generated by Django 2.0.8 on 2019-03-20 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0036_auto_20190311_1339'),
        ('adesao', '0036_merge_20190320_1151'),
    ]

    operations = [
    ]
