# Generated by Django 2.0.8 on 2019-03-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0039_sistemacultura_data_publicacao_reatificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='data_publicacao_reatificacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
