# Generated by Django 2.0.8 on 2018-09-19 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0008_auto_20180917_1105'),
        ('gestao', '0002_auto_20180626_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diligencia',
            name='ente_federado',
        ),
        migrations.AddField(
            model_name='diligencia',
            name='sistema_cultura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adesao.SistemaCultura'),
        ),
    ]
