# Generated by Django 2.0.8 on 2018-09-20 16:25

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension

class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_auto_20180626_1401'),
    ]

    operations = [
        UnaccentExtension(),
    ]
