# Generated by Django 2.0.8 on 2018-09-27 17:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adesao', '0010_sistemacultura_ente_federado'),
        ('gestao', '0004_auto_20180919_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiligenciaSimples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_diligencia', models.TextField(max_length=200)),
                ('classificacao_arquivo', models.IntegerField(blank=True, choices=[(0, 'Em preenchimento'), (1, 'Avaliando anexo'), (2, 'Concluída'), (3, 'Arquivo aprovado com ressalvas'), (4, 'Arquivo danificado'), (5, 'Arquivo incompleto'), (6, 'Arquivo incorreto')], null=True)),
                ('data_criacao', models.DateField(default=datetime.date.today)),
                ('tipo_diligencia', models.CharField(choices=[('geral', 'Geral'), ('componente', 'Específica')], max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adesao.Usuario')),
            ],
        ),
    ]
