# Generated by Django 2.0.8 on 2018-10-03 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0006_remove_diligenciasimples_tipo_diligencia'),
        ('gestao', '0005_auto_20180927_0955'),
    ]

    operations = [
    ]
