# Generated by Django 2.0.8 on 2018-10-10 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_auto_20180920_1325'),
        ('gestao', '0007_merge_20181003_0945'),
    ]

    operations = [
    ]
